# Generated by Django 2.1.4 on 2018-12-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="Nom de l'application")),
                ('app_token', models.CharField(editable=False, max_length=150, null=True, verbose_name="Token d'acces")),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(help_text='Identifiant du client dans la BD du server', null=True, verbose_name='ID in app')),
                ('currently_connected', models.BooleanField(null=True, verbose_name='Utilisateur actuellement connecter')),
                ('current_connection_id', models.CharField(max_length=100, null=True)),
                ('last_connection', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu de la notification en JSON')),
                ('received_date', models.DateTimeField(auto_now=True, verbose_name='Date a laquelle il est arriver sur le serveur')),
            ],
        ),
    ]
