# Generated by Django 2.1.4 on 2018-12-12 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='app',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='notifications',
            field=models.ManyToManyField(to='core.Notification'),
        ),
        migrations.AlterField(
            model_name='client',
            name='currently_connected',
            field=models.BooleanField(default=False, null=True, verbose_name='Utilisateur actuellement connecter'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_connection',
            field=models.DateTimeField(null=True),
        ),
    ]
