# Generated by Django 2.1.4 on 2018-12-12 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181212_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Application'),
        ),
    ]
