# Generated by Django 2.1.4 on 2018-12-13 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181212_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='internal_uuid',
            field=models.CharField(default=1, max_length=50, verbose_name='Identifiant interne'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Application', verbose_name='application'),
        ),
    ]
