# Generated by Django 2.1.4 on 2018-12-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181213_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='notifications',
        ),
        migrations.AddField(
            model_name='notification',
            name='clients',
            field=models.ManyToManyField(to='core.Client'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='internal_uuid',
            field=models.CharField(editable=False, max_length=50, verbose_name='Identifiant interne'),
        ),
    ]
