# Generated by Django 2.1.4 on 2018-12-17 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
        ('core', '0005_auto_20181216_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description of the app'),
        ),
    ]
