# Generated by Django 2.1.4 on 2018-12-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181217_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Application still alive'),
        ),
    ]
